import json
import os
import funcoesUteis
from botocore.vendored import requests

TOKEN = os.environ['TELEGRAM_TOKEN'] #Bot token generated by BotFather
BASE_URL = "https://api.telegram.org/bot{}".format(TOKEN)

def main(event, context):
    try:
        data = json.loads(event["body"])
        message = str(data["message"]["text"])
        chat_id = data["message"]["chat"]["id"]
        first_name = data["message"]["chat"]["first_name"]

        response = "Olá {}! Sou o bot do UberHub💜.\n\nMeus comandos são:\n/eventos Lista de eventos 🚀\n/vagas Lista as vagas de emprego 🏢\n/noticias Confira as news 📰".format(first_name)

        if "/eventos" in message:
            response = funcoesUteis.buscarAgenda()
        
        if "/vagas" in message:
            response = funcoesUteis.buscarVagas()
        
        if "/noticias" in message:
            response = funcoesUteis.buscarNoticias()

        data = {"text": response.encode("utf8"), "chat_id": chat_id}
        url = BASE_URL + "/sendMessage"
        requests.post(url, data)

    except Exception as e:
        print(e)

    return {"statusCode": 200}